# Generated by Django 3.1.8 on 2021-08-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='city',
        ),
    ]
