# Generated by Django 3.1.8 on 2021-08-13 08:34

from django.db import migrations, models
import subscribers.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_remove_clothing_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=subscribers.models.imageFile),
        ),
    ]
